### ISSUE TITLE
host folder not getting created

### ISSUE THREAD

**Issue by dheidelberger** [Inventsable/bombino-vue-basic#1] opened 2020-02-02 21:46 UTC
This is a fantastic tool, thanks for creating it and making it available! It seems like the bombino-vue-basic template isn't creating a host folder with the various .jsx scripts. Not sure if this is by design and the README is incorrect or if the README is correct and the folder isn't getting written.

**Comment by dheidelberger** [comment] 2020-02-02 21:49
Likewise, the main (utilities) folder isn't being written either.

**Comment by Inventsable** [comment] 2020-02-02 22:15
Hello, thanks and good catch! I've updated this repo to include the host folder, you should be able to run the command again (no need to update bombino) and get correct results.

> Likewise, the main (utilities) folder isn't being written either.

This part is actually by design for basic, since I include utilities either via npm packages (cep-spy, starlette, and optionally cluecumber for a few templates) already I only included the menus component inside ./src/components.

The README is likely outdated since this is 3rd generation, and I copy/pasted from previous templates (generator-cep-vue-cli). Let me know if you find anything else or have any other troubles, I'm actually working on a new template that really overhauls utilities alongside a component library for Adobe CEP at the moment

**Comment by Inventsable** [comment] 2021-08-24 00:45
Closing this unless new issues arise from outdated documentation on this template

**Closed as completed by Inventsable** 2021-08-24 00:45 UTC
